[package]
name = "massa_signature"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = { version = "0.4", features = ["check"] }
secp256k1 = { version = "0.20", features = ["rand-std"] }
serde = { version = "1.0", features = ["derive"] }
# custom modules
massa_hash = { path = "../massa-hash" }

[dev-dependencies]
serial_test = "0.5"
serde_json = "1.0"

[features]
hash-prefix = []
