[package]
name = "massa_final_state"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
# custom modules
massa_ledger = { path = "../massa-ledger" }
massa_models = { path = "../massa-models" }
massa_async_pool = { path = "../massa-async-pool" }

[dev-dependencies]
massa_ledger = { path = "../massa-ledger", features=["testing"] }
massa_async_pool = { path = "../massa-async-pool", features=["testing"] }

[features]
testing = []
