[package]
name = "massa_execution_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
thiserror = "1.0"
tracing = "0.1"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
massa_final_state = { path = "../massa-final-state" }
massa_ledger = { path = "../massa-ledger" }


[features]
testing = ["massa_ledger/testing", "massa_models/testing"]
