[package]
name = "massa_network_exports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.15", features = ["full"] }
enum-map = { version = "2.0.3", features = ["serde"] }
# custom modules
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
serde_json = "1.0"
tempfile = { version = "3.2", optional = true } #used with testing feature

[dev-dependencies]
massa_models = { path = "../massa-models", features = ["testing"] }


[features]
instrument = [ "massa_models/instrument", "massa_time/instrument"]
testing = ["massa_models/testing", "tempfile"]
