[package]
name = "massa-node"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"
build = "../build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.15", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
# custom modules
massa_api = { path = "../massa-api" }
massa_async_pool = { path = "../massa-async-pool" }
massa_bootstrap = { path = "../massa-bootstrap" }
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_consensus_worker = { path = "../massa-consensus-worker" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_execution_worker = { path = "../massa-execution-worker" }
massa_logging = { path = "../massa-logging" }
massa_final_state = { path = "../massa-final-state" }
massa_ledger = { path = "../massa-ledger" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_network_worker = { path = "../massa-network-worker" }
massa_pool = { path = "../massa-pool" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_protocol_worker = { path = "../massa-protocol-worker" }
massa_storage = { path = "../massa-storage" }
massa_time = { path = "../massa-time" }



[features]
beta = []
instrument = ["tokio/tracing", "massa_api/instrument", "massa_bootstrap/instrument", "massa_consensus_exports/instrument", "massa_consensus_worker/instrument", "massa_network_exports/instrument", "massa_pool/instrument", "massa_protocol_exports/instrument", "massa_protocol_worker/instrument","massa_network_worker/instrument"]
sandbox = ["massa_consensus_exports/sandbox", "massa_consensus_worker/sandbox", "massa_models/sandbox"]

[build]
rustflags = ["--cfg", "tokio_unstable"]

